# -*- coding: utf-8 -*-
"""E-Commerce sales Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Eh7Mk-uz8mEPyaYJ1YSH5IwGvIUhO2A
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/E-Commerce sales/SuperStoreUS.csv')
df.head()

df.info()

df.isnull().sum()

"""#Data cleaning"""

df['Product Base Margin'].fillna(df['Product Base Margin'].mean(),inplace=True)

"""#Count of order priorities"""

df['Order Priority'].value_counts()

df['Order Priority'].unique()

df['Order Priority']=df['Order Priority'].replace('Critical ','Critical')

sns.countplot(x='Order Priority',data=df,width=0.4)
plt.show()

df.info()

"""#Count of Ship Mode"""

df['Ship Mode'].value_counts()

sns.countplot(x='Ship Mode',data=df,width=0.4)
plt.show()

x=df['Ship Mode'].value_counts().index
y=df['Ship Mode'].value_counts().values

plt.figure(figsize=(3,4))
plt.pie(y,labels=x,startangle=60)
plt.show()

sns.countplot(x='Ship Mode',data=df,hue='Product Category')
plt.show()

df['Product Category'].value_counts()

"""#Countplot foe Customer Segment"""

sns.countplot(x='Customer Segment',data=df)
plt.show()

sns.countplot(x='Product Category',data=df[df['Product Category']=='Office Supplies'],hue='Product Sub-Category')
plt.show()



df['Order Date']=pd.to_datetime(df['Order Date'],format='%d/%m/%Y')

df['Ship Date']=pd.to_datetime(df['Ship Date'],format='%d/%m/%Y')

df.info()

df.head()

df['Order Month']=df['Order Date'].dt.month

df.groupby('Product Category',sort=False).agg({'Profit':'sum'})

"""#Profit by Product Category"""

sns.barplot(x='Product Category',y='Profit',data=df,estimator=sum,)
plt.show()



df['State or Province'].value_counts()[:5]

df['Order Month'].value_counts()

df['Order Month'].value_counts()

"""#Count of Sales per Month"""

sns.countplot(x='Order Month',data=df)
plt.show()